### ISSUE TITLE
Teaser addition appears to be broken

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#323]
Please do work for this task in a branch called issue-323.

I just tried adding a Teaser for the Google Summer of Code to radgrad.ics.hawaii.edu. The teaser was added successfully, but when I tried to display it in the public explorer, the teaser video does not run, and the console shows this:

![Screen Shot 2019-08-10 at 10 41 50 AM](https://user-images.githubusercontent.com/290288/62826706-c26f4180-bb5b-11e9-96fc-6b86c61fe462.png)

This also appears to be happening for logged in users.

**Comment by cammoore** [comment]
The problem is the URL field. It is miss-labeled. The value in the field should just be the video ID not the full URL to watch the video. For the Google Summer of Code the URL field should be S6IP_6HG2QE not the full URL. I updated the field in RadGrad. The page now looks like:
<img width="1351" alt="Screen Shot 2019-08-12 at 9 35 20 AM" src="https://user-images.githubusercontent.com/1194643/62892677-9206df00-bce4-11e9-9d54-a4d043eb3809.png">

**Comment by cammoore** [comment]
I've updated the Add, List, and Update Teaser widgets to reflect that the 'URL' should be the ID of the Youtube video, not the full URL to the video.
