### ISSUE TITLE
Implement Student Explorer pages

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#61]
Please do all work for this issue in a branch called issue-61.
Implement the explorer pages.

**Comment by amymalia** [comment]
<img width="1215" alt="screen shot 2017-01-15 at 4 55 36 pm" src="https://cloud.githubusercontent.com/assets/2596254/21969591/8343c68e-db43-11e6-86d1-f4983cba5ffd.png">
Here is the current version of the explorer. Currently, there are 5 explorers: Career Goals, Courses, Degrees, Interests, and Opportunities. Users can navigate through the explorers using the dropdown menu on the left side. Users can then navigate through the explorer's pages using the menu on the left side, underneath the dropdown menu. Explorer pages are listed first by Added/Not Added, and then alphabetically by name (courses are alphabetically by shortName, since that is the name that appears on the menu). Each explorer page has its own unique URL using the following pattern: 

`http://localhost:3000/student/abi/explorer/interests/artificial-intelligence`

Once on an explorer page, users can see available information about the item such as description, date, related interests, prerequisites, etc. To add to the social aspect of RadGrad, users can also see small circular images of other users who are interested in that item as well. Users can also add/remove items to their plan/interests directly through the explorer. 

TODO: There are small things I would like to fix. Such as, the explorer home page should either be a bit more interesting or route directly to an explorer. Also, there is a bug on the opportunity page where a Teaser video will remain from the previous page, only when switching directly between two pages containing a teaser video. Will return to this at a later time.
